# Generated by Django 5.2.5 on 2025-08-24 16:54

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=api.models.generate_reference, max_length=12, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=api.models.generate_reference, max_length=12, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_sold', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=api.models.generate_reference, max_length=12, unique=True)),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.car')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=api.models.generate_reference, max_length=12, unique=True)),
                ('scheduled_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.broker')),
                ('client_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.clientrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=api.models.generate_reference, max_length=12, unique=True)),
                ('viewer_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bargained_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_details', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('scheduled_view', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.scheduledview')),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=api.models.generate_reference, max_length=12, unique=True)),
                ('terms', models.TextField()),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_view', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.scheduledview')),
            ],
        ),
        migrations.CreateModel(
            name='SoldCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=api.models.generate_reference, max_length=12, unique=True)),
                ('sold_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.car')),
                ('processed_sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.processedsale')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default=api.models.generate_reference, max_length=12, unique=True)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sold_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soldcar')),
            ],
        ),
    ]
