# Generated by Django 5.2.5 on 2025-08-26 06:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_broker_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('interested', 'Interested'), ('not_interested', 'Not Interested')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='broker',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
    ]
