# Generated by Django 5.2.5 on 2025-08-28 07:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_broker_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedsale',
            name='paid_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='processedsale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank'), ('other', 'Other')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='broker',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
    ]
