# Generated by Django 5.2.5 on 2025-08-28 07:43

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_processedsale_paid_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='processedsale',
            name='scheduled_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_sales', to='api.scheduledview'),
        ),
    ]
