# Generated by Django 5.2.5 on 2025-08-30 12:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_broker_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='preferred_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
    ]
