# Generated by Django 5.2.5 on 2025-08-30 15:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_clientrequest_preferred_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='viewingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('sold', 'Sold')], default='pending', max_length=15),
        ),
    ]
