# Generated by Django 5.2.5 on 2025-08-31 07:54

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_broker_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='scheduled_view',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.viewingrequest'),
        ),
        migrations.RemoveField(
            model_name='clientrequest',
            name='preferred_datetime',
        ),
        migrations.RemoveField(
            model_name='processedsale',
            name='scheduled_view',
        ),
        migrations.AddField(
            model_name='processedsale',
            name='viewing_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.viewingrequest'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='processedsale',
            name='paid_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='processedsale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('financing', 'Financing')], default='cash', max_length=20),
        ),
        migrations.DeleteModel(
            name='ScheduledView',
        ),
    ]
