# Generated by Django 5.2.5 on 2025-08-31 10:14

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_broker_reference_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='scheduled_view',
        ),
        migrations.AddField(
            model_name='agreement',
            name='agreement_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='agreements/'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='car_color',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='car_model',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='car_year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='agreement',
            name='client_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='agreement',
            name='sold_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='api.soldcar'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='sold_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='terms',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
    ]
