# Generated by Django 5.2.5 on 2025-08-31 10:25

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_agreement_scheduled_view_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='sold_car',
        ),
        migrations.AddField(
            model_name='agreement',
            name='sold_car_id',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
    ]
