# Generated by Django 5.2.5 on 2025-09-01 06:16

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_agreement_sold_car_agreement_sold_car_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
    ]
