# Generated by Django 5.2.5 on 2025-09-01 06:28

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_broker_reference_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientrequest',
            old_name='scheduled_datetime',
            new_name='preferred_datetime',
        ),
        migrations.AlterField(
            model_name='broker',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
    ]
