# Generated by Django 5.2.5 on 2025-09-02 09:02

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_broker_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
    ]
