# Generated by Django 5.2.5 on 2025-09-04 09:04

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_agreement_reference_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='api.car'),
        ),
        migrations.AlterField(
            model_name='processedsale',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='soldcar',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='viewingrequest',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
    ]
