# Generated by Django 5.2.5 on 2025-09-04 14:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_ondemandcar_alter_agreement_reference_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ondemandcar',
            name='broker_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ondemandcar',
            name='owner_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ondemandcar',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='processedsale',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='soldcar',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='viewingrequest',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
    ]
