# Generated by Django 5.0.3 on 2025-09-08 12:59

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_ondemandview_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ondemandcar',
            name='owner_contact',
        ),
        migrations.RemoveField(
            model_name='ondemandcar',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='ondemandsale',
            name='broker_commission',
        ),
        migrations.AddField(
            model_name='ondemandcar',
            name='broker_contact',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ondemandcar',
            name='company_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ondemandview',
            name='negotiated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='ondemandcar',
            name='broker_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='processedsale',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='soldcar',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='viewingrequest',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='OnDemandEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('call', 'Call'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('interested', 'Interested'), ('not_interested', 'Not Interested'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='contacted', max_length=20)),
                ('negotiated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='api.ondemandcar')),
            ],
        ),
    ]
