# Generated by Django 5.0.3 on 2025-09-08 12:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_ondemandcar_owner_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='clientrequest',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='ondemandcar',
            name='broker_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='processedsale',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='soldcar',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='viewingrequest',
            name='reference_number',
            field=models.CharField(default=api.models.generate_reference, max_length=12, unique=True),
        ),
    ]
